import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafd', padding: 20 },
  row: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  label: { fontWeight: 'bold', fontSize: 17, marginRight: 10, color: '#222' },
  dateBox: {
    backgroundColor: '#f0f4fa',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 18,
    minWidth: 120,
    borderWidth: 1,
    borderColor: '#e0e6ed',
  },
  dateText: { fontSize: 16, color: '#222' },
  infoBox: {
    backgroundColor: '#f8fafd',
    borderRadius: 12,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1.5,
    borderColor: '#dbeafe',
    shadowColor: '#b0c4de',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  infoText: { fontSize: 15, color: '#333', marginBottom: 3 },
  radioGroup: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  radio: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#d0d7e2',
    marginRight: 10,
    backgroundColor: '#f0f4fa',
  },
  radioSelected: {
    backgroundColor: '#2563eb',
    borderColor: '#2563eb',
  },
  radioText: { color: '#222', fontWeight: 'bold', fontSize: 15 },
  radioTextSelected: { color: '#fff' },
  actionBtn: {
    backgroundColor: '#e0e6ed',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginLeft: 8,
  },
  actionBtnText: { color: '#2563eb', fontWeight: 'bold', fontSize: 15 },
  gameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    shadowColor: '#b0c4de',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  deleteBtn: { marginLeft: 8 },
  resultInput: {
    width: 40,
    height: 36,
    borderWidth: 1,
    borderColor: '#d0d7e2',
    borderRadius: 6,
    textAlign: 'center',
    marginHorizontal: 2,
    backgroundColor: '#f8fafc',
    fontSize: 15,
  },
  resultInputDisabled: { backgroundColor: '#f0f4fa', color: '#aaa' },
  startBtn: {
    backgroundColor: '#2563eb',
    borderRadius: 10,
    padding: 16,
    alignItems: 'center',
    marginTop: 28,
    marginBottom: 30,
    shadowColor: '#2563eb',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  startBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 18, letterSpacing: 1 },
  gameGridTable: {
    borderWidth: 1.5,
    borderColor: '#d1d5db',
    borderRadius: 12,
    marginBottom: 18,
    backgroundColor: '#f8fafd',
    shadowColor: '#b0c4de',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  gameGridRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f8fafd',
    minHeight: 48,
  },
  gameGridRowBottom: {
    borderBottomWidth: 0,
    backgroundColor: '#f4f7fb',
  },
  gameGridCellDelete: {
    width: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderColor: '#e5e7eb',
    minHeight: 48,
  },
  gameGridCellWide: {
    flex: 1,
    minWidth: 120,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderColor: '#e5e7eb',
    minHeight: 48,
    paddingHorizontal: 8,
  },
  gameGridCellWideLast: {
    borderRightWidth: 0,
  },
  gameGridDeleteBtn: {
    padding: 4,
    borderRadius: 6,
    backgroundColor: '#fee2e2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gameGridDeleteIcon: {
    color: '#ef4444',
    fontSize: 22,
    fontWeight: 'bold',
  },
  gameGridInput: {
    width: 60,
    height: 36,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 6,
    textAlign: 'center',
    backgroundColor: '#f3f4f6',
    fontSize: 15,
  },
  scoreLabel: {
    color: '#888',
    fontSize: 13,
    fontWeight: 'bold',
  },
  readonlyBg: {
    backgroundColor: '#f1f1f1',
  },
  readonlyText: {
    color: '#999',
  },
  readonlyBtn: {
    backgroundColor: '#e5e7eb',
    borderColor: '#e5e7eb',
  },
  readonlyDeleteBtn: {
    backgroundColor: '#f3bcbc',
  },
  readonlyInput: {
    backgroundColor: '#f5f5f5',
    color: '#999',
    borderColor: '#e0e0e0',
  },
  readonlyPicker: {
    backgroundColor: '#f5f5f5',
    color: '#999',
    borderColor: '#e0e0e0',
  },
});

const pickerSelectStyles = {
  inputIOS: {
    fontSize: 16,
    height: 40,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    color: '#222',
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#eee',
    marginBottom: 4,
    textAlign: 'center',
  },
  inputAndroid: {
    fontSize: 16,
    height: 40,
    paddingHorizontal: 12,
    borderRadius: 8,
    color: '#222',
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#eee',
    marginBottom: 4,
    textAlign: 'center',
  },
  iconContainer: {
    top: 10,
    right: 12,
  },
  placeholder: {
    color: '#aaa',
    textAlign: 'center',
  },
};
